PagueVeloz/Models/Fornecedor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PagueVeloz.Models
{
    public class Fornecedor
    {
        public int for_id { get; set; }
        
        public string for_nome { get; set; }

        public DateTime for_data_cad { get; set; }
        public int emp_id { get; set; }

    }
}

PagueVeloz/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagueVeloz.Util;
using PagueVeloz.Models;
using System.Data.Entity;

namespace PagueVeloz.Controllers
{
    public class FornecedorController : Controller
    {
        // GET: Fornecedor
        public ActionResult Index()
        {
            List<String> TEmpresa = new List<String>();

            PagueVelozEntities db = new PagueVelozEntities();
            ViewBag.SelectListEmpresas = new SelectList(db.Empresas.OrderBy(c => c.emp_nome).ToList(), "emp_id", "emp_nome");
            
            TEmpresa.Add("Pessoa Física");
            TEmpresa.Add("Pessoa Jurídica");

            ViewBag.TipoEmpresa = new SelectList(TEmpresa);
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            PagueVelozEntities db = new PagueVelozEntities();
            ViewBag.SelectListEmpresas = new SelectList(db.Empresas.OrderBy(c => c.emp_nome).ToList(), "emp_id", "emp_nome");
            FornecedorPageModel model = new FornecedorPageModel();
            List<String> TEmpresa = new List<String>();

            TEmpresa.Add("Pessoa Física");
            TEmpresa.Add("Pessoa Jurídica");

            ViewBag.TipoEmpresa = new SelectList(TEmpresa);
            if (form["TipoEmpresa"] == "Pessoa Física")
            {
                Empresa emp = db.Empresas.Find(int.Parse(form["lbEmpresas"]));

                if(DateTime.Parse(form["fornecedorCPF.for_nascimento"]).AddYears(18) >= DateTime.Now && emp.emp_uf=="PR")
                    ModelState.AddModelError("fornecedorCPF.for_nascimento", "Pessoas físicas do PR devem ter mais de 18 anos");

                if (!CPF.isValid(form["fornecedorCPF.for_cpf"]))
                    ModelState.AddModelError("fornecedorCPF.for_cpf", "CPF Inválido");
            }
            else
            {
                if (!CNPJ.isValid(form["fornecedorCNJP.for_cnpf"]))
                    ModelState.AddModelError("ffornecedorCNJP.for_cnpf", "CNPJ Inválido");

            }







            Fornecedor_Fisica fornecedorFisica= new Fornecedor_Fisica();
            Fornecedor_Juridica fornecedor_Juridica= new Fornecedor_Juridica();
            Telefone tel = new Telefone();
                Fornecedor fornecedor = new Fornecedor
                {
                    for_nome = form["fornecedor.for_nome"],
                    emp_id = int.Parse(form["lbEmpresas"])

                };
                if (form["TipoEmpresa"] == "Pessoa Física")
                {
                    fornecedorFisica = new Fornecedor_Fisica
                    {
                        for_CPF = form["fornecedorCPF.for_cpf"],
                        for_RG = form["fornecedorCPF.for_RG"],
                        for_nascimento = DateTime.Parse(form["fornecedorCPF.for_nascimento"])
                    };


                }
                else
                {
                    fornecedor_Juridica = new Fornecedor_Juridica
                    {
                        for_cnpf = form["fornecedorCNJP.for_cnpf"]
                    };

                }

                string[] telefones = form["Telefones"].Split('\n');

                foreach (string str in telefones)
                {
                    tel = new Telefone
                    {
                        tel_numero = str
                    };

                }
            if (ModelState.IsValid)
            {
                db.Fornecedors.Add(fornecedor);
                db.SaveChanges();

                if (form["TipoEmpresa"] == "Pessoa Física")
                {
                    fornecedorFisica.for_id = fornecedor.for_id;
                    db.Fornecedor_Fisica.Add(fornecedorFisica);
                }
                else
                {   
                    fornecedor_Juridica.for_id = fornecedor.for_id;
                    db.Fornecedor_Juridica.Add(fornecedor_Juridica);
                }

                tel.for_id = fornecedor.for_id;
                db.Telefones.Add(tel);
                db.SaveChanges();

                ViewBag.Msg = "Cadastro Efetudo com sucesso";
                fornecedor = new Fornecedor();
                fornecedorFisica = new Fornecedor_Fisica();
                fornecedor_Juridica = new Fornecedor_Juridica();
                tel = new Telefone();

            }

            model.fornecedor = fornecedor;
            model.fornecedorCNJP = fornecedor_Juridica;
            model.fornecedorCPF = fornecedorFisica;
            model.telefone = tel;
            ViewBag.emp_id = int.Parse(form["lbEmpresas"]);


            return View(model);

        }

        public ActionResult Lista(string filtro, FormCollection form)
        {
            List<String> filtros = new List<String>();
            filtros.Add("Nome da Empresa");
            filtros.Add("Data Cadastro");

            ViewBag.filtros = new SelectList(filtros);

            PagueVelozEntities db = new PagueVelozEntities();

            List<FornecedorPageModel> modelo = new List<FornecedorPageModel>();

            System.Linq.IOrderedQueryable Fornecedores;
            switch (filtro)
            {
                case "Nome": 
                Fornecedores = db.Fornecedors.OrderBy(x => x.for_nome);
                    break;
                case "Data":
                    Fornecedores = db.Fornecedors.OrderBy(x => x.for_data_cad);
                    break;
                default:
                    Fornecedores = db.Fornecedors.OrderBy(x => x.for_nome);
                    break;
            }



            foreach (Fornecedor item in Fornecedores)
            {
                FornecedorPageModel iModelo = new FornecedorPageModel();
                iModelo.fornecedor = item;
                iModelo.empresa = db.Empresas.Where(x => x.emp_id == item.emp_id).FirstOrDefault();
                if(db.Fornecedor_Fisica.Where(x => x.for_id == item.for_id).FirstOrDefault() != null)
                    iModelo.fornecedorCPF = db.Fornecedor_Fisica.Where(x => x.for_id == item.for_id).FirstOrDefault();
                else
                    iModelo.fornecedorCNJP = db.Fornecedor_Juridica.Where(x => x.for_id == item.for_id).FirstOrDefault();
                modelo.Add(iModelo);


            }


            return View(modelo);
        }


    }
}

PagueVeloz/Views/Fornecedor/Index.cshtml
@model PagueVeloz.Models.FornecedorPageModel
@using PagueVeloz.Models


@{
    ViewBag.Title = "Index";
}

<h2>Fornecedores</h2>


<h1>@ViewData["Msg"]</h1>

@using (Html.BeginForm("Index", "Fornecedor", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Cadastro de Fornecedores</legend>
        <div>
            @Html.Label("Empresas")
            @Html.DropDownList("Empresas",
                        ViewBag.SelectListEmpresas as SelectList,
                        "--Selecione uma empresa--",
                        new { @class = "form-control", @id = "Empresas" })
            @Html.ValidationMessage("Empresas")


            <input type="hidden" id="lbEmpresas" name="lbEmpresas" value="@ViewBag.emp_id" />
        </div>
        <div class="editor-field">

        </div>
        <div class="editor-label">
            @Html.Label("Nome")
        </div>
        <div class="editor-label">
            @Html.EditorFor(model => model.fornecedor.for_nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
                @Html.ValidationMessageFor(model => model.fornecedor.for_nome)
        </div>
        <div class="editor-label">
            @Html.Label("Tipo da Empresa")

        </div>
        <div>
            @Html.DropDownList("TipoEmpresa",
                        ViewBag.TipoEmpresa as SelectList,
                        new { @class = "form-control" , @id= "TipoEmpresa"})

        </div>
        <div class="editor-field">
            <div id="panelCPF">
                <div>
                    @Html.Label("CPF ")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.fornecedorCPF.for_CPF, new { htmlAttributes = new { @class = "form-control", @placeholder = "(___.___.___-__)" } })
                    @Html.ValidationMessageFor(model => model.fornecedorCPF.for_CPF)
                </div>
                <div>
                    @Html.Label("RG")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.fornecedorCPF.for_RG, new { htmlAttributes = new { @class = "form-control", @placeholder = "RG" } })
                    @Html.ValidationMessageFor(model => model.fornecedorCPF.for_RG)
                </div>
                <div>
                    @Html.Label("Data de Nascimento")
                </div>
                <div>
                    @Html.TextBoxFor(model => model.fornecedorCPF.for_nascimento, "{0:dd/MM/yyyy HH:mm}", htmlAttributes: new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.fornecedorCPF.for_nascimento)

                </div>
            </div>

            <div id="panelCNPJ" hidden>
                <div>
                    @Html.Label("CNPJ ")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.fornecedorCNJP.for_cnpf , new { htmlAttributes = new { @class = "form-control", @placeholder = "(__.___.___/____-__)" } })
                    @Html.ValidationMessageFor(model => model.fornecedorCNJP.for_cnpf)
                

                </div>
            </div>

        </div>
        <div class="editor-label">
            @Html.Label("Telefones")
        </div>
        <div class="editor-field">
            @Html.TextArea("Telefones", new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefones" } })
        </div>
        <br />
        <div class="btn-toolbar">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="submit" class="btn btn-danger">Limpar</button>
        </div>

    </fieldset>
    @section Scripts{
        @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#TipoEmpresa").change(function () {

                if ($("#TipoEmpresa Option:Selected").text() == "Pessoa Física") {
                    $("#panelCNPJ").hide();
                    $("#panelCPF").show();
                } else {
                    $("#panelCNPJ").show();
                    $("#panelCPF").hide();
                }
            })
        })

       
    </script>
        <script>
             $(document).ready(function () {
                 $("#Empresas").change(function () {
                     $("#lbEmpresas").val($("#Empresas Option:Selected").val().toString());
            })
        })
        </script>
    }


}

PagueVeloz/Views/Fornecedor/Lista.cshtml
@using PagueVeloz.Models
@model IEnumerable<PagueVeloz.Models.FornecedorPageModel>



@{
    ViewBag.Title = "Lista";
}

<h2>Lista de Fornecedores</h2>
<div class="form-group row">
    <div class="col-sm-10">

        @Html.DropDownList("Filtros", 
                                    ViewBag.filtros as SelectList,
                                    new { @class = "form-control col-sm-10", @id = "Filtros" })

        <button type="submit" class="btn btn-primary" onclick="redirect()">Aplicar Filtro</button>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome Fantasia</th>
            <th scope="col">UF</th>
            <th scope="col">Nome da Empresa</th>
            <th scope="col">CPF/CNPJ</th>
            <th scope="col">Data do Cadastro</th>
        </tr>
    </thead>
    <tbody>

        @foreach (PagueVeloz.Models.FornecedorPageModel Item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(mItem => Item.fornecedor.for_id) </td>
                <td>@Html.DisplayFor(mItem => Item.fornecedor.for_nome) </td>
                <td>@Html.DisplayFor(mItem => Item.empresa.emp_uf) </td>
                <td>@Html.DisplayFor(mItem => Item.empresa.emp_nome) </td>
                @if (Item.fornecedorCPF != null)
                {

                    <td>@Html.DisplayFor(mItem => Item.fornecedorCPF.for_CPF) </td>
                }
                else
                {
                    <td>@Html.DisplayFor(mItem => Item.fornecedorCNJP.for_cnpf) </td>
                }

                <td>@Html.DisplayFor(mItem => Item.fornecedor.for_data_cad) </td>
            </tr>
        }
    </tbody>

</table>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
    <script type="text/javascript">
        function redirect() {
            if($("#Filtros Option:Selected").val().toString()=="Nome da Empresa")
                location.href = "/Fornecedor/Lista?Filtro=Nome";
            else
                if ($("#Filtros Option:Selected").val().toString() == "Data Cadastro")
                    location.href = "/Fornecedor/Lista?Filtro=Data";
                else
                    location.href = "/Fornecedor/Lista?Filtro=CPF";


                

        }

    </script>