PagueVeloz/Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace PagueVeloz.Models
{
    public class Empresa
    {
        [Display(Name="Estado")]
        [Required(ErrorMessage = "Selecione o Estado!")]
        public string emp_uf { get; set; }
        [Display(Name="CNPJ")]
        [Required(ErrorMessage = "CNPJ Requerido!")]
        public string emp_cnpj { get; set; }
        [Required(ErrorMessage = "Nome Requirido!")]
        [Display(Name="Nome")]
        public string emp_nome { get; set; }
    }
    public enum Estados
    {
        AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO
    }
}

PagueVeloz/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagueVeloz.Models;
using PagueVeloz.Util;

namespace PagueVeloz.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Lista()
        {
            PagueVelozEntities db = new PagueVelozEntities();
            return View(db.Empresas.ToList());
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            if (!CNPJ.isValid(form["emp_cnpj"]))
            {
                ModelState.AddModelError("emp_cnpj", "CNPJ inválido!");
                ViewData["Msg"] = "";


            }

            Empresa emp = new Empresa
            {
                emp_nome = form["emp_nome"],
                emp_cnpj = form["emp_cnpj"],
                emp_uf = form["emp_uf"]
            };

            if (ModelState.IsValid)
            {
                PagueVelozEntities db = new PagueVelozEntities();
                db.Empresas.Add(emp);
                db.SaveChanges();
                ViewData["Msg"] = "Cadastro efetuado com sucesso";
                emp = new Empresa();
            }
            return View(emp);
        }

    }
}

PagueVeloz/Views/Empresa/Index.cshtml
@model PagueVeloz.Empresa  

@{
    ViewBag.Title = "Index";
}

<h2>Empresas</h2>


<h1>@ViewData["Msg"]</h1>

@using (Html.BeginForm("Index","Empresa",FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Cadastro de Empresa</legend>
        <div>
            @Html.LabelFor(model => model.emp_nome)
        </div>
        <div class="editor-field">
                @Html.EditorFor(model => model.emp_nome,new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome fantasia" } })
                @Html.ValidationMessageFor(model => model.emp_nome)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model=> model.emp_uf)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.emp_uf,
                    new SelectList(Enum.GetValues(typeof(Estados))),
                    "Selecione o Estado",
                    new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.emp_uf)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.emp_cnpj)

        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp_cnpj , new { htmlAttributes = new { @class = "form-control", @placeholder = "(__.___.___/____-__)" } })
            @Html.ValidationMessageFor(model => model.emp_cnpj)


        </div>
        <br />
        <div class="btn-toolbar">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>

    </fieldset>
    @section Scripts{ 
        @Scripts.Render("~/bundles/jqueryval")
        };      

    }